a = input()
b = input()
c = input()
d = input()
e = input()
f = input()
g = input()
h = input()
i = input()
j = input()
print(a.capitalize())
print(b.capitalize())
print(c.capitalize())
print(d.capitalize())
print(e.capitalize())
print(f.capitalize())
print(g.capitalize())
print(h.capitalize())
print(i.capitalize())
print(j.capitalize())